export enum Operation {
  BALANCE_TO_BALANCE = 1,
  TRANSFER_FROM_CARD = 2,
  TRANSFER_TO_CARD = 3,
  PAYMENT_FROM_BALANCE_TO_BALANCE = 4,
  PAYMENT_FROM_CARD_TO_BALANCE = 5,
  PAYMENT_FROM_CARD_AND_BALANCE_TO_BALANCE = 6
}
